#
#changed DIR_ROOT
#
export DIR_ROOT=$(shell pwd)/..

#
#don't change it
#
include $(DIR_ROOT)/mk/define.mk

#
#changed me, append sub-system
#
SUB_SYSTEM=appkey atcookie umc umd stimerc stimerd smonitorc smonitord atenv atsys jlogger jlogd

#
#don't change it
#
include $(DIR_ROOT)/mk/template.mk