#ifndef __LIB_OEM_OEM1_H__
#define __LIB_OEM_OEM1_H__
/******************************************************************************/
#define OEM1_NAME               "raytight"

#define OEM1_BASE_INITER __OEM_BASE_INITER( \
    OEM1_NAME,  \
    OEM_MAC,    \
    OEM_SN,     \
    OEM_TYPE,   \
    OEM_VERSION)

#define OEM1_LSS_SERVER         "its.raytight.com"

#define OEM1_LSS_INITER __OEM_LSS_INITER( \
    OEM_LSS_USER,   \
    OEM_LSS_PWD,    \
    OEM1_LSS_SERVER,\
    OEM_LSS_PORT)

#define OEM1_RSYNC_SERVER       "its.raytight.com"

#define OEM1_RSYNC_INITER  __OEM_RSYNC_INITER( \
    OEM_RSYNC_USER,     \
    OEM_RSYNC_PWDFILE,  \
    OEM_RSYNC_PATH,     \
    OEM1_RSYNC_SERVER,  \
    OEM_RSYNC_PORT,     \
    OEM_RSYNC_TIMEOUT)

// raytight/lms/ca.crt.c
#define OEM1_LMS_CA \
    "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lKQUxETVozVkVp" \
    "U3VFTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmt4RnpBVkJnTlYKQkFNTURpb3VjbUY1ZEdsbmFIUXVZ" \
    "Mjl0TUI0WERURTJNREV4TXpBMU16RXpNVm9YRFRNMk1ERXdPREExTXpFegpNVm93R1RFWE1CVUdB" \
    "MVVFQXd3T0tpNXlZWGwwYVdkb2RDNWpiMjB3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJE" \
    "d0F3Z2dFS0FvSUJBUURFTHJPdk96Uk1IeTdlZFNOU3Q5OWw2Z3RKUGNqTjJZUjlQNlB1Q0I0amY1" \
    "ODkKaWJGcmw3aEI5S2xQTExkZU1oeTdXbnJYYTFOaW54RXBEdmFHQmphOGpLSnJHV0dkTmlkSlZv" \
    "ejBrdzZLd3ZzTQpZSXlLUzdRQzdmSnh5RFhMcHZUd0tqV3lsazd1cmZzZ1hDRTJpQXZ4aEVVazE2" \
    "dmtVbllIMzJsd3B4YW1nN2FKCmRvVjUxVG8yMEFxY1ZBdzkySUJ3R2xkdEU3eWhvSzVnM2x0TlRp" \
    "T1RHeHVSNDlZckh6eStJOWF5OEl6TURGYisKYVYrN0FHVWxuQzF1TUtubDNHRXdCZ3h4TVMzYnRt" \
    "SWlkN2NLNnVGb1FSbURrNlFaNithcHJKd0JOMzU0VXdGeAphSjkwRWFvdXE4VUh0SkdoUlZmSjZn" \
    "ZzdUTGdIV0JCU2RxZ1YyL3NsQWdNQkFBR2pVREJPTUIwR0ExVWREZ1FXCkJCU2FFdW1ZQmpOUjdH" \
    "K3ZLRGVVOGtlSDBIVzljakFmQmdOVkhTTUVHREFXZ0JTYUV1bVlCak5SN0crdktEZVUKOGtlSDBI" \
    "VzljakFNQmdOVkhSTUVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkZiL2J0VVNV" \
    "bgpCZzJLc3A4OUpKWHpsT29lWVU3NFlQNUg3QUpCU3hqYWRlVXA3a0JTRk4rQ2dPMXZGQ1VHN3NL" \
    "RnJNWHlTT2l0ClVkbUtJVSttZkJybE0vK2hrVWdxaXVTTkYxVnJ2QnJZV1E1UHRmMnRsZDhKNm9Q" \
    "bnI4Tis5ZVhHRDFtRmpNWjEKa1pHMXJVczJscGVrc0tva0J1ZmRPTUtJTHBNM3pFVjhRTDhQVkUv" \
    "dkJQa0hrM2VEQ1Q3eXhVaE43UTdENFVyUgpWWXpYQ1FSUXhsRG9tRVpMSFFkckJuN3RjclJ2bTVv" \
    "RnRzYllvdGp1anVKZDRXMFpVcW9HUCtWcmhRS2hnQWtkCitlVjd6dVM5WXhLSG85bGZXbjdxQmxH" \
    "ODhJRmw1bnFLRTdDaXdTWEJuaVZkaVVKTDcyeWNUeHNBMHB3KzZrc0MKSmkwYTJ6eWdVZjNNCi0t" \
    "LS0tRU5EIENFUlRJRklDQVRFLS0tLS0K" \
    /* end */

// raytight/lms/client.key.c
#define OEM1_LMS_KEY \
    "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeDlmS2kwbnRU" \
    "TStxUzFPQkZvZmJ6MFVjU1JuSXVoVWdVTXQvanBTci9GQ1E1VENsCmtqOXowNHBNUFRqUHcrQlg2" \
    "WjUrUytTTGMwNUd4bXZTdmUrbFh4S09WMEMwZ0dJV0ZkOENHK2JHTTFzYTdzRDkKYUoyMi9aUyt0" \
    "L2ZiQzYzZ1RWd1N1TDBBRmFCTm02WW9JQytuVjZhSTdCYytmUDBCRGtnWTkxYWNHTUVqWUdkMwpL" \
    "WmFYanpGZ0VvZGErSmhCYmVHRUFJa1VuaXhmOTR3ZkdxVXRYVTZLUXJWMmFWYWx3QzNYME5GeGI0" \
    "ZEppOHUxCjVuZEZHZ1hXTWhTSWpac1JRRHRDYmxWVnYrM1NCZHdOWHFrTjhua3AwMFpIR3VQSTBB" \
    "dXNod0d1MjlsdkFQL0MKajFGQ0g5OXgvMEhmQ3NJTHNwYUhjK3owcmhIYVVpMVJiR3YyRFFJREFR" \
    "QUJBb0lCQUY5bW5xUjcrREt3K0VUWgpha2lOTnR2dHpDRUJsQmR4T21vWG01OC9UaE0zaXRRK3N1" \
    "dnNLcWtUM20xamo1dWNuNXRCTkYyYWp3L09rRzdzCnprQXFCVElyczVQbnFjT1lENThGUlFaNDFx" \
    "bHhscHZmdVptVm9PUFJmSEpxZWtGTEVrY2I2endSemRhRkhrZHQKdkw0UXdieFFIaEZHejJmdmgr" \
    "OS9iNXV6MXZUaGRrczZITWZkRWF1Z1ZaalQzOFpFZjc2SnpNUEJQVTY2VC83UwpscFVNbEVNTFJL" \
    "LzRMMExIWGttNERkeVlnUnNtTjk3cTBVeDZBbC93dzNubkVBZDVuL1FoUkNKZEE0OGZXOTNrCitZ" \
    "MzZlZE1oU0g3V3BHQkRmbUZjaThTbFpjQ2Joek9GbGFPdTBFdWthTm92bmhPSnRVN1VCaFdUNHVQ" \
    "MUFqTXEKN3JGczh5a0NnWUVBOFplcUQvQjN3RDd1VGtXMGhyTmV4VmptdmNxVXFsald4M3hzZDk1" \
    "NXdsUnpESFdMbFNVcwptRThwY2dhbkN1ZmpNN21aZzBkUlYweDYvM3ZoWGhCVEVuTXFGck1oMHY2" \
    "Q2tCUURTc3pua3BGSHJRbis1S3BQCml6S2VzWWJFdW5JVVgySWxQNGRHTFh5VWIyTHJkdFFvMjgr" \
    "UEtHejBGbE9ZQi8xRkNqSk9kVnNDZ1lFQTA4Sy8KTkF5c2lNbXcrL1dnVGhkbVg4dGpwZGdad0c4" \
    "QXpVZ3d4cXpxZktGVjF1Wkc1dEtSa2RmTnltR0dIUHphaWtRawpGdGJrdlZScUlTcnRsUGtXSG5n" \
    "NFhQb2RwY2FkbHJTM1REM1Z4cjZRVTVnYno0R05BSVJRWVozMHN3akx1U04wCk5DeDhHVGRrVG9I" \
    "ak9oNmIzVEI1WVRVQjdsZnNlWHZkRFlsMDFyY0NnWUFjelN6c0M0bnJORlZxcFdxNUtFY2oKRmM4" \
    "a1R6TmIvNDFUYU9UeGdXZFlvSUs2dUlTMGVpTVA0Vmdhak9wN0pWdnp2YXVzZCtNZG1qT0xvN1Fo" \
    "WjZiUApxMFVZUWJERm02dnJDMGU5TWlKbFdjYUd2WXRTclc4Z05CK3hJRlR4dVVudWVSL2hxL25V" \
    "MEdaTnhTZzNHV0hwCm1wd0JnTU8wcWJDVk96OXcwTUNEd3dLQmdGVDArK3J3N3NPT1Q1QTJjbE1D" \
    "TmxOV2NTc1hNUFd3VXgwSXluRGEKN05TRmtiKys4VkVueDdsQVlGTENuNkMvblJuOXpwRFBORVAx" \
    "T3dNRml2M0tsU0l5VDBLV0loRGhSMVl3T0ozQQo3U1JvVGRVTDRKUjJ3RkFseFczMGhqalIzWkh3" \
    "ZEcxK0wyZWFmb2EwdTZvVW42bTFDZTJDNjd4b3ovbkpSTjFxCmVWS3ZBb0dCQUtFb0dzaEdLV2VJ" \
    "UmwwUHBsK2JrekM3OVRDelN1ekJvYWRhLy9wcXZGb1BJZHgwaUpldWNmUzEKTFIwc2ZZc1FnWk1x" \
    "S0JXYlRnOWhxSkJWUytNOGs4ZzllcEJjWFYwVFhwUmJNdzRoakU0UG9xcVRiS2JQcnpkdgoySWRM" \
    "VVBia25NNTd3RHZBWGw3Z3g0KzdTalk0T3AyRnU2OUVXcXZHbzhkUTB6UFVMbEZhCi0tLS0tRU5E" \
    "IFJTQSBQUklWQVRFIEtFWS0tLS0tCg==" \
    /* end */

// raytight/lms/client.crt.c
#define OEM1_LMS_CERT \
    "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5VENDQWJHZ0F3SUJBZ0lKQU5FdWhLSFIw" \
    "RU9hTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmt4RnpBVkJnTlYKQkFNTURpb3VjbUY1ZEdsbmFIUXVZ" \
    "Mjl0TUI0WERURTJNREV4TXpBMU16RXpORm9YRFRNMk1ERXdPREExTXpFegpORm93RmpFVU1CSUdB" \
    "MVVFQXd3TEtpNXNkR1ZtYVM1amIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdn" \
    "Z0VLQW9JQkFRREgxOHFMU2UxTXo2cExVNEVXaDl2UFJSeEpHY2k2RlNCUXkzK09sS3Y4VUpEbE1L" \
    "V1MKUDNQVGlrdzlPTS9ENEZmcG5uNUw1SXR6VGtiR2E5Szk3NlZmRW81WFFMU0FZaFlWM3dJYjVz" \
    "WXpXeHJ1d1AxbwpuYmI5bEw2Mzk5c0xyZUJOWEJLNHZRQVZvRTJicGlnZ0w2ZFhwb2pzRno1OC9R" \
    "RU9TQmozVnB3WXdTTmdaM2NwCmxwZVBNV0FTaDFyNG1FRnQ0WVFBaVJTZUxGLzNqQjhhcFMxZFRv" \
    "cEN0WFpwVnFYQUxkZlEwWEZ2aDBtTHk3WG0KZDBVYUJkWXlGSWlObXhGQU8wSnVWVlcvN2RJRjNB" \
    "MWVxUTN5ZVNuVFJrY2E0OGpRQzZ5SEFhN2IyVzhBLzhLUApVVUlmMzNIL1FkOEt3Z3V5bG9kejdQ" \
    "U3VFZHBTTFZGc2EvWU5BZ01CQUFHakZ6QVZNQk1HQTFVZEpRUU1NQW9HCkNDc0dBUVVGQndNQ01B" \
    "MEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkhOQlJGOGZhZDE1NHNLTFJ4T3daU1YyK1MKUFJuMitP" \
    "ZlBnZ3ZTS28yV3Y3MHUvc0hmLzYyL2R4bmZaeis2ZEZvcUZSMVBQbGpmWlhMNzR1Lzc2MFhldVZC" \
    "cgphVDFTNDZEZVMzcEJSNU5zNDhtU0lvTElHK2RDL21ENUtQUnVkc3duMkNMZnhxSi8ra1ZDY0tB" \
    "VzdnTWtHSTRKCmxpdjN5SjM2alc3MHV6Wml6eUdMWXJOSmoyNnVObE1NRWxMTFlzMGhkT2NlR1N3" \
    "SlB3aUdNVWFxdEROdUhFa1MKUnpPVU9LZ3BQNTJlaVFqRGNDcldhVjRnczgrenRKNks4cGZyaGZ1" \
    "V0o4dy90ZzYyLzQ4WWFBMmZqeUh4WkFIZwp1c1IwNnBoNEVSTVhrMG5NVmVkaHRWR1Zpakl1S1lK" \
    "UE5OOXhUQ2g0ZnEvQXJxSkpDMU9uYVBnb3pWNWMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=" \
    /* end */

#define OEM1_CERT_LMS_INITER {      \
    [OEM_CERT_CA]   = OEM1_LMS_CA,  \
    [OEM_CERT_KEY]  = OEM1_LMS_KEY, \
    [OEM_CERT_CERT] = OEM1_LMS_CERT,\
}   /* end */

// raytight/lss/ca.crt.c
#define OEM1_LSS_CA \
    "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZCVENDQXUyZ0F3SUJBZ0lKQUs3VmlialJK" \
    "U04zTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmt4RnpBVkJnTlYKQkFNTURpb3VjbUY1ZEdsbmFIUXVZ" \
    "Mjl0TUI0WERURTJNREV4TXpBMU16RTBNMW9YRFRNMk1ERXdPREExTXpFMApNMW93R1RFWE1CVUdB" \
    "MVVFQXd3T0tpNXlZWGwwYVdkb2RDNWpiMjB3Z2dJaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUNE" \
    "d0F3Z2dJS0FvSUNBUURPcndya3hFa0t2d201cmR3L2UxTVN6YmNOWHBWaXY4V0h4VHpCQktFbDd2" \
    "YisKanMwV3YyMTJVZGRzUi9qMWxHOEVPbWE2NnhKMUovOERvWkYrd3YrYVhGaEo0Yi9kbVRCa3Vl" \
    "UWpkWGd3cHFCVApBbFFYNC9jS0Vlc05GVHZMbWtSRjNXSFpSc0YzR1JsaWM0aDMrT0N5aTBiZ0x3" \
    "b2RabThNa25RalQ4Z05yNDErCmxjUCtIM2JmU0JyeEtCcStXbzdjeWRzLy9BbTJ5eGRXREk2ZGNF" \
    "YUtIWmhmWDlkRUtoN0FEV2MrbkRCSDM0bHcKV2tIYW5vOE9sc3cxbU8wSkY4RDlnOVRYUHJYc2Zv" \
    "UllRekRvTCs2Sk01eXpHY3dkQXFseTUycnIzRk1JclY2QgozaFhJYzN6N2ZOckhtK3lBWkxXM2VH" \
    "L3VLeVZobkZtOVRIM2ZqRy92ZEJYMVhscVZPOFhnUVYrZVZuNDYxWkw0ClFyZmpXN3I1Rk1VekdM" \
    "cFdqREwwd0xUU1prclhDWEZyTE40cFdieTJvMHIvYXQ2ZnEvQU1kSFdxcGFuYlhRUi8KOWh5K3Zh" \
    "OXBxK0ZUNVVNSVdGWVdKaVVsRjUzZTUxREhwbkFoR2ZJZHIwMGVsU3Rib1BWdm5DbDNYcGFkbyt5" \
    "cAo2QmtPQjB0dC8rZkUrdklkL1dqVzh0VDFuY29wSkdQR2VzZWhwVTMvYXE2V0xlT0FMbHBsQmhS" \
    "NjY3dXJTUUNvCnhwRmFxWjlrNFpZSVBJcW9hcTZTUFZrVVpuaGV2T0tkZTFHckFOYTMvdS8yK1J4" \
    "UURLTHZrTkQ3cUFxUHkxVEMKVHlUeHV4dzlJL1dTTmN3bUJkaElQeDVOSHZpU2ZhdVZWL2JSMzFu" \
    "R2MyczZTYnNIY3FYOXpXUngybG5PandJRApBUUFCbzFBd1RqQWRCZ05WSFE0RUZnUVVLbnhwTEFF" \
    "SFg2aGcxM3J2a3c5SWZxQzNLS3d3SHdZRFZSMGpCQmd3CkZvQVVLbnhwTEFFSFg2aGcxM3J2a3c5" \
    "SWZxQzNLS3d3REFZRFZSMFRCQVV3QXdFQi96QU5CZ2txaGtpRzl3MEIKQVFzRkFBT0NBZ0VBS0Ns" \
    "RkFjU0tWUzVMdUpTb2lPRnlkcFRXSDlWZmN1WGYxVFg5K2NYei9nb3d4S0V5aFE3bApvK2FocmFu" \
    "U2dmY3YzYU0zUnJqY3lCcUlsWU41MmNDT1JaNU5laHVYUnNBZmsxZUhVMjBTVytaNUV2OXRyamR1" \
    "CjBUY2lxbSsxZ2dEQ0JRdXdCdUQ1VTJiMW93ZUdGSStVeVBLbWpIVzdRNmNpMnliRVNFV2ZNS0lN" \
    "OW9RdGpqM2EKUjR3US9OMC9lMnNqTWgrZU5WVzhMTDF4V2N2LytvSS9OMnJrblphbjRyMi90YU1Z" \
    "MHo3NnpWelU4MDdHa3czSgpuM2x1V3F2ckJGaUZIZTliNFk5MjZRMVBoeDk3WmpZSGdROHZ4NEZC" \
    "bWQ2bWVjdEYwaU5ncGl2aEJldGt5RFNzCjg3RGIvSVo5QnpiSVNRNlcrMFVPSlpkYUJtRExUU2pK" \
    "bDBZVUtrVVpINVVQZHNrY2g4d2UyMWJEMXM5eCtyV3UKVzd2OFlQOFNTRjZYV2t4cngyWE9qM1pL" \
    "ZHhqSmJBMFIyL0lieHIwVVFESW5CU0h4dHJ6ZW1ZVy9hSlEzWDFmegpzUHlTMnNrMUhVNzJzTWNV" \
    "b0FwdWhTK0NHd0xqMm12RWkwY0ZCYWtEaDZIK0o0VGQ5QlJPQWJic1RiZmNjOFhtCm9lblJhY0dS" \
    "eFM2UHdSdzU1QWxtek1UVEs3Q3NaUmorNm1Ka1gxTEExOW1MRis5c0dBVEFvZVYxMTRDdXlIWXEK" \
    "aEl2SC93ZjY5MGU2OVJ4T0NxMGRjQ3IvY0ZLUW1CUEQzUWR5bDNmc2UySGRnZ0wvVUMyYmw4Tnhh" \
    "UnlXNHQ2agpCOXlLaDY4MTVsOE1YYjhTa2krUitVTjBzSWtRYjhwRmVwdlNhb3BVRU5TNDJacTBS" \
    "MGdBaFNvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==" \
    /* end */

// raytight/lss/client.key.c
#define OEM1_LSS_KEY \
    "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKSndJQkFBS0NBZ0VBMDlmUTl6d2xx" \
    "TmFPeHkxM2toSFljNDJ2ZkVZTW11TnVRd2NUcUJudUg4cldPdmxWCk0rS2dXUE9UUlMzZlVka1lp" \
    "N3pOOVV0b3dJeU92REFtMGJBWndZbVlJbGVKditNelk1SEJpdzVxbEFGZUlHL2gKcnc5Z29xUWdr" \
    "OUtCdTc1OG9WL2s4MWRlcHY2aDRmRU93elJJN1lvNjBXZFYwZDhHbGNjOXpQemJEekg4YjNHQQpK" \
    "RVd0Q2pnM3VLSForcnRkQkx4OFlXUEV1YVU0N2lIOXVUY1VLVzF2R1U4Q3IrNWNRRjJQSE1aMnVk" \
    "bmU5emIzClZQaW9kZWpGVElOZEJsTml3eFpPb0FYbjIwWW1UbXBVcjhZWnZoNmdKM2lzMEZIcy82" \
    "eXA1WCtHL01zRGFqQW4KQWFreitBNDZhU2xMQ21KdGdaaU1LbUo3c0ZBY1hJNjFrMDZFaDJBeUJF" \
    "bVRNc0NKblFFUUJRVHJqeWxzY1RjdgpoeDQ3bDVKem8xTDRhdThKcTBBT3pBV3FoUU5jVFJZVlhn" \
    "ZUdRNkowaGxFbi95NFhZRk81b2huWkVqbnpQTWlYCnE1WUw3RVE0SEJaS2tNdDNUK3k0Sk9peWtM" \
    "bVBBalpYejhiaCtHTXRUd2I5Q1RBcG94MXFCTUF6RGducWZxY3EKckNZL1FoMHMrTFlTdC9WaStQ" \
    "c0JWVGtLVXorY1FRWXExV2t4VU5ZQ1RDMjBZZURXOVlFOG03QzV2YnNpZkpkNQpMcHhwTVdnRXoz" \
    "WWwrRDNMd1ZJS3lhVFIwM2YrNUpKdW5oaXVjbVlQSitkQ3BEbEs0dG5tZkZIemZTODZQdkRJCnhr" \
    "eWxZaWx3aFNSd3FrYmFucFpqMEhuZXByRjJSK2NvM2xQZXg4RGxaMDdZMCtTKzE4SzI2SzJUcjNz" \
    "Q0F3RUEKQVFLQ0FnQUpCWXpocW84VUJLY3A5bGE4UXNSTUQ0R2tzanNCTWFSVmVHeXU0UVBTR01w" \
    "TTBxZDlRUzZBKzBhUApVS2ZORFlqTkVxcFd3dkpnR054UFNXR3QxbWtTWS9DMXJiS3hHRlRzN1ow" \
    "bmRlSzJFT1RZVHN0MnNCbjJjelRyCjlyQU50Y3dLOTFHQngzdkJjdUNrQmFjU1N4eTcrUUlPUHU5" \
    "WnM3ek5EaUlrbzdRVWpwVm9qWlhlZFpVcjlUN3kKUHZwUWdrQXczbklSbDdVZUR0cEEwZlBET29S" \
    "Q1MyWEsxeUdQS29DRlFUYkNDL1dzYm9uZlQxanpKbS9PTGE2UgpWcHJVbFNLRW1tT1l6d2VUd0FZ" \
    "TG10Mm1hckpYOVdmdXBtWDlyUytCcC9ISVUwa0ZaUVB0TnNYQ2ZWazRQQ3JpCnBaNkxmNnVZTkUz" \
    "cjFDdmVVMXNSMmdZRGt2bHowcHVRU25uTnJSUlFvR3Bla3AvdUcrYlNuUUpxU0IxTE9vZ00KOUlZ" \
    "dEZMbEp4T3NOQklaTzFXMVE1VlVSUjVpUDlxcWtFakFqNEM1RmpXcWMvZzZVMFFPRjRDd3BMeTVm" \
    "UkIvQwo4YWR1UUVMc3hmak9NYS9YelEwNWFiZDN5cFBGMHh5bzRkM2xhUklRMEVKdFNoRTladGp6" \
    "QjkrNmwrNFFwZWNRCkhLeXFBZkdqOGV5V0tDMVV5ajJOd2RPT2x3WVhqRG94d0FvSjB6SFZMNEZj" \
    "QzhQU2s0bmdhTEdKNEZ4bElLRisKZSt6WVNBdG03cExTTEx0SnpzN3lXVFpZTE93cEpnZk0ybmx2" \
    "aHN1eTYzOUExSythcEpwRnZlSWVrY0pzZm9GRApuOFQ4dkRPSEFqbEtldzJJa3VXd0YwMElWZ0Zs" \
    "anZCRUMrREQxVXM2VDUxbmZtZVYrUUtDQVFFQTh2TXY5SUVCCk4zV0pXZUoxNFMwV01hVEszZmZK" \
    "T0JXN25TMVRtZUU3ZmM1WVl4TFJrSm9GMnZncTZGM3RKNm9KS2hrcHdnaGkKNUs5VzRzYzVMejg1" \
    "SmxCcHdicENHZEw3MUdSWnRjczZuSXdSeU1zamFSUklMTFV4d2FQVHIvRzVsVFVnblExaQpVeU0y" \
    "Q3F0Q3Z4eWRidDdvNWdPQnl0aDBGU1ZJMzZ4eTBnQWU0Uk1Dd2R1WnNkUUp5R0FjYngwcmtTYVl5" \
    "VEM3Cktma3VJQVJkdnhhWTV6RmRCVjIwdmd5dThPamliYU10cUM3eDlJbTJLc3ZOQkpVdEdzcHBT" \
    "RjQvcXZ2d25KZnMKanlXYXhJdEQ2ekI2L0dmL1RkUGVFY0d2Zm91NEpLWFBYazlpYmkrVFVqLzZh" \
    "UHVjc2xzMXBYeTBoeGVyM0xKegpyMFVhSVh1VWJTenJ6UUtDQVFFQTN6amdiNm1GN29aN21iSHF4" \
    "WmIyMCt3YnhSVHpzU3V5c3RkZmlkZEtVNUk3CmRHK2x2bW5OYkJHOGZWWDVlMEVTcENVdFZsUExs" \
    "aXBVM2M2eElncCs4eUtEY0ZmcitleVZsY3hTelowbnpLckMKREV5LzluMEk1MkVueUM2cC9qYVBj" \
    "S1J3T1JGaGJvdms3UVpYN1RvVHhnZ0UyUVhyTU4rTkw1YmRvYTNYN241NApqQ3RuQ0lUeXBTUFpB" \
    "YThxMkJRWDJSdGIzZm0yTWJjZzN1d25GK1hqSHU0WjdGNHl5c3lrZmdYbTJXMDNwMWdjCmdjSHls" \
    "c2crOFk0ZDBPcWRReDdBczNkNjlWWnNiaU5LTE5KV3hIYVNwTmRhZjBuOEpTYlE4VndIaEFCZ0Vz" \
    "M20KRFRXN3l4SFI4U0p1bEFBN1YrbVhMMTBCYXV2S2dzcnp3dFFoWE5RUVp3S0NBUUI5Z3BiMnFL" \
    "SzVSUFpsUWpJRgoxMllNMVlhY2I0TTdmemJDZDRVbURRN1A2b2NNLzg3Vjlrd3FHR1VLVUdQUlJ1" \
    "MmZHd3JRbThhRFAvWVNDRHdKCnBZN2Z0VkU5YlB6ekhHVlBEMXl0SjBXclZFMW52MUlXMmd5RFZF" \
    "UlZOazZKS2NiblIyQUc0c0EyRlEyNUswcTcKTW93K2w5Z1g1QjNzYmpCaU1EWGFuOXRkbEFSZjRK" \
    "TmZGUlRzb284L1BpL1NVMjZMZVRZYlVocVBENVQ5bzJQTwo4VnlpcTRUVDNkb2ZDS3hqOXR2cktn" \
    "N1BRUmxzYkt4NHBYclA4RVV4L3ZtdkVrbXdDcUgrTkJwWXhXT1VRQ0loCllaVlh5bDVCbGIrMnlx" \
    "bmdKVXhIV29XcndqVW1tVnR4ZFczblNIMW1RdXFQQ01LMnU4cmtwQ2hSbHRCdUZjclQKTUE3TkFv" \
    "SUJBQUdIZ1RvaW5qRkpLSldmKzJ6SklQM0lzMVFCVmI0VC81QnNHMUoxY0NQc2I0M1hxZm9JL1lo" \
    "TgpBczZWQlRXTDk1VzZUM28wN3NNam5Sczc3RWpBYTZnOHgwdkF2blFpNDg5MzYrVk91MVFTbzJ1" \
    "MEp1aUlhTVExCkRURzQ2Qjgrdm5MV0haSzJoTVZlSGY1bHVicDlXRjlWOUxxTDZOV1g0bjY5K055" \
    "L3RTZ0VJODFLQ3RXckc0SjQKSVdkNmpMK1lPNldZSTJQODd2dWVOcEp3YWNBbktnd3ZNMnhFSlBM" \
    "d3ZmdkRESmJXd2JmYXlhODE1ZlNVZ0tIbApDRjFERGpyRWZpdDhtUklQT29UeXB2SnhxbmlFRzNN" \
    "WHFwNE9vclNhZEhvQzJHWldIbEppcUwzVWJXbnh3RTkzCm5leFRxQlJ0SEVVTnpSR3ZkZDY1aHp3" \
    "QmVnMEp3dWNDZ2dFQVF4UExmRnJhRGt6OEduRnFKOFdiOE9QTmtaanYKVytUaVZpblF1Mmt0Q0RQ" \
    "dndoVURBc0xpVUpTS0lKQWVHdDFHS1Znclo0SHQ5ZFIzZzZ3a2w3QTlVaUJjSzNibwo3TUx0S2xD" \
    "Q3dDWFNHRVhqQ29FaFpGUU95dFhOTjJxMnY0L3dMUThxN2VGTGU1UTVSZSsxMEJwczlYNWRvRldL" \
    "Ck1iT09GWEdlQ21UMWhvQ3l4ZktZVXhHZytGNFYxV2JSK2tCN0ZBMUZTTW92MncrTU5wTmxaRFJi" \
    "NHd3VFo2dEMKdkc5SU0rdUtoemExQVNjMkV3VDc2R3hvb2lPZG45L1d0Q0cxMEhvUGUyVEYrQ0tw" \
    "Sk5RUXhFaHRvZnZncjJjego1V21JbHNaRUdoUHNBOU1Wa2Z6NWlkNFV1Z3dBb05GNFYzK0xlMldF" \
    "cTVMc2ZRc0sxVGZURXMxbHh3PT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K" \
    /* end */

// raytight/lss/client.crt.c
#define OEM1_LSS_CERT \
    "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV5VENDQXJHZ0F3SUJBZ0lKQVAxRFhiMEkw" \
    "VUduTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmt4RnpBVkJnTlYKQkFNTURpb3VjbUY1ZEdsbmFIUXVZ" \
    "Mjl0TUI0WERURTJNREV4TXpBMU16RTFOVm9YRFRNMk1ERXdPREExTXpFMQpOVm93RmpFVU1CSUdB" \
    "MVVFQXd3TEtpNXNkR1ZtYVM1amIyMHdnZ0lpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElDCkR3QXdn" \
    "Z0lLQW9JQ0FRRFQxOUQzUENXbzFvN0hMWGVTRWRoemphOThSZ3lhNDI1REJ4T29HZTRmeXRZNitW" \
    "VXoKNHFCWTg1TkZMZDlSMlJpTHZNMzFTMmpBakk2OE1DYlJzQm5CaVpnaVY0bS80ek5qa2NHTERt" \
    "cVVBVjRnYitHdgpEMkNpcENDVDBvRzd2bnloWCtUelYxNm0vcUhoOFE3RE5FanRpanJSWjFYUjN3" \
    "YVZ4ejNNL05zUE1meHZjWUFrClJhMEtPRGU0b2RuNnUxMEV2SHhoWThTNXBUanVJZjI1TnhRcGJX" \
    "OFpUd0t2N2x4QVhZOGN4bmE1MmQ3M052ZFUKK0toMTZNVk1nMTBHVTJMREZrNmdCZWZiUmlaT2Fs" \
    "U3Z4aG0rSHFBbmVLelFVZXovcktubGY0Yjh5d05xTUNjQgpxVFA0RGpwcEtVc0tZbTJCbUl3cVlu" \
    "dXdVQnhjanJXVFRvU0hZRElFU1pNeXdJbWRBUkFGQk91UEtXeHhOeStICkhqdVhrbk9qVXZocTd3" \
    "bXJRQTdNQmFxRkExeE5GaFZlQjRaRG9uU0dVU2YvTGhkZ1U3bWlHZGtTT2ZNOHlKZXIKbGd2c1JE" \
    "Z2NGa3FReTNkUDdMZ2s2TEtRdVk4Q05sZlB4dUg0WXkxUEJ2MEpNQ21qSFdvRXdETU9DZXArcHlx" \
    "cwpKajlDSFN6NHRoSzM5V0w0K3dGVk9RcFRQNXhCQmlyVmFURlExZ0pNTGJSaDROYjFnVHlic0xt" \
    "OXV5SjhsM2t1Cm5Ha3hhQVRQZGlYNFBjdkJVZ3JKcE5IVGQvN2trbTZlR0s1eVpnOG41MEtrT1Vy" \
    "aTJlWjhVZk45THpvKzhNakcKVEtWaUtYQ0ZKSENxUnRxZWxtUFFlZDZtc1haSDV5amVVOTdId09W" \
    "blR0alQ1TDdYd3Jib3JaT3Zld0lEQVFBQgpveGN3RlRBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFj" \
    "REFqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFISWV2Cmc2aDRlcU0xU0lXSTdUQ2IvdlR3Mldr" \
    "dTNrY2JNdjBvUWR4bmR5TEVEMHprTWVoNHNmc2twSWZJMi9ycURDS0sKa2xLRkFDSDAyUnlaRkhD" \
    "eW00dVQwQmdqODRQT05yeVNSNGxuMW12bVBaL2llRXhmOHliV1lrQUo2NC9xRVprYQp1Nlluamt1" \
    "UUpRWUdyb0laZE84U1l0TjRzRGhIMFE3Z3Z1ZTJIb3BEN05GUXZGVUQ3UUJRMnZkZnNjU3laTzVV" \
    "CjUwcG1CNUZmcHgxSjNJb1cvbkZRUjhVeUJOS2xKdldNZHRvL2ZTMEg2dVplNERpU2EzbWJZRnMr" \
    "WElZNVlNNVYKWFp2RGdwVkwyMk5zLzlZTjVHZGtza1ZWL3J0YnR5dGZDK05kSlVJQmh6YXdXa3Iy" \
    "cDRzbXJLRE5SMU56dEI1Zwoyd0JURmJWNWZaNkJzcVZpRXlNSk5wR0puMlo2NnBXa3AvWlNJcFh3" \
    "dWhKZWVrb1pYcVdEdFlOTXdwUzJ4ak1TCmw2eVBIakkwQVBMV1Z6V21WeElvVzVHQzNYUjVERWNL" \
    "NVFTVHo1aUxacVdEdXBPUENMYkNiWDVNWDc2VGYvaU4KOURFQm1oUFg3ZVQxNjJlUFVDZ1dJOTc0" \
    "M0IvbzUvV0JzOWNFOEp4RXZsWTRJREsyWjh1eEN3dURJZ0FGSTBheQpLMVBZOXE4WFppbjVFeW9n" \
    "L0ozeldpYit5c1YxYVZRWmxWUy9JMG5iVmpVR0x3MWdEZmUrVGtHdVFzcDVFZ0lqCmw5eHBvemdX" \
    "VlpkaGFidHc1cHhWSjk5WHFYVWpZS1p5UjVxZE1mYXNxMjMyaWtZNmNwdzNqdmFEKzVJVzJxM08K" \
    "VnYxSXd3a1loTW9UeHpKSDc4UlpyZWtmU0E3V1NjeGlsa2l5aENjPQotLS0tLUVORCBDRVJUSUZJ" \
    "Q0FURS0tLS0tCg==" \
    /* end */

#define OEM1_CERT_LSS_INITER {      \
    [OEM_CERT_CA]   = OEM1_LSS_CA,  \
    [OEM_CERT_KEY]  = OEM1_LSS_KEY, \
    [OEM_CERT_CERT] = OEM1_LSS_CERT,\
}   /* end */

// raytight/ums/ca.crt.c
#define OEM1_UMS_CA \
    "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lKQUpFQjhVWjZv" \
    "Zjh5TUEwR0NTcUdTSWIzRFFFQkN3VUFNQmt4RnpBVkJnTlYKQkFNTURpb3VjbUY1ZEdsbmFIUXVZ" \
    "Mjl0TUI0WERURTJNREV4TXpBMU16SXdNRm9YRFRNMk1ERXdPREExTXpJdwpNRm93R1RFWE1CVUdB" \
    "MVVFQXd3T0tpNXlZWGwwYVdkb2RDNWpiMjB3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJE" \
    "d0F3Z2dFS0FvSUJBUURDMmZnS2V5N0lzc1ZsSk5ESkNlQUNEZkNVSTJKN1JIck5qVFpBNEpuOEZt" \
    "Ry8KRnd4KzhoUGd6aDJnRE9NN3Q1R1FhcCtGckRuQUppNnY1ZkJHUmRpUEZEdCtPTmtmRHpNcWo2" \
    "UXRFYnEzUG1LRgpaTWRINElTZGQyUEdIaEprdUgvT1VOMnVQKzRxZUVvR2hwSmZSdHF1UjFzR2tx" \
    "Z05IVFp2R2lJUmhnWnR1aFVzCk1tSFBoV0VyQmJXb3h2STRjSTZJenFsSEo0RGdGTldNNnFWK0dR" \
    "ZllXd2FnYXVuSXBicU1LWHhoRncwTkRGK0MKTzgraHduZmFCMERKakRzM3U1eG90U2FIbi9HaWpo" \
    "UUxQNkh3UkgxcHJaVTczU3htdFJxbGoxbnR6cXFKTk1HLwpWdExDcEhOZnNHREFieUZWaHZudUhP" \
    "ZFNOZVhsM0RqdTBCTUhsM2MzQWdNQkFBR2pVREJPTUIwR0ExVWREZ1FXCkJCVHU3WnNIWkxxZEtv" \
    "QnBMeWFZSnNPYWkva1djREFmQmdOVkhTTUVHREFXZ0JUdTdac0haTHFkS29CcEx5YVkKSnNPYWkv" \
    "a1djREFNQmdOVkhSTUVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWxYK1gxOHRJ" \
    "ZwppMU5CL3BXeWE2K0xucEU1ZUNmalh2NFNKMU00V3lsWUpnRzV0TDdBZ09IY21CSmVYdG9DUGZI" \
    "bDZIYW1HSXBYCkhRUTJ3bHUvUHNEZDdLeHl1aTNhNVUwQXNBY3JyQ0lpTjV0YlR4TVFiTkZMTkxh" \
    "Sm8wYUxocDd3bWIyOGNuYWYKS3BsUHhVNlF2VkFPVEZTdDJOOHRDMEhTUmlaN2hDYjRFTFlJNGJn" \
    "VmUyVlFUVlNydUFrNVBQdTh3NktmakN3Vgp4WkNhMTVhb0FLVGFCVS8rUWhsdGtCWGdtQ2Z4QWRB" \
    "L21ObTg3Wmp6RjZta256YUVaVFE5QzIwanQ4anQwUVI2Cm5IaDRKL1E1djZSSmZCNVgzV3plZ3ZS" \
    "bEdyWW5tR3FrQyt2L1ozNTUranlEU1cvenhhQzdQbUgvYkJkQkNUaTYKNjNLdm9qNmxNQnZnCi0t" \
    "LS0tRU5EIENFUlRJRklDQVRFLS0tLS0K" \
    /* end */

// raytight/ums/client.key.c
#define OEM1_UMS_KEY \
    "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeHhrbGoxeXhw" \
    "N3ZFeWRLR0N0cVBPNUZFLyt0MmRZRGRTN0IzdkNWYXlYTFd4OUptCnNKVjFaSHBlbGx4YlVpVjVx" \
    "Tmc3cUlKTG53a3I0T2ZjNVZ3TnByOC81dkxPTG9hWUtLMXRTek5lVUc1TjgxcE4KM2RjVTJmbjlo" \
    "T1hhT0FyTGZRRnBMNGFPY1MvOHZuUENBVXNsVWYyT1V5M1hpZmJjZCthYTZ1OEV1Qy8yMHp1VApO" \
    "dWVyYk1ZQ0xEMFBlc09MSTFXUG93RlFlYnAwUmI5dCtOK2dZbGt6eTBXOWxENHJlcmZVaENnemMy" \
    "VFBFYk83CllHV0Rpd1RYazRoQmxyQ0tlakNocFlJS1ZsVEE1MTJRaU9RSkZGQkhRYVdDczJ6UndL" \
    "TGxPZEFkenkzOW9GMjUKUFV0Q2VRazBBaVNhT25adm9BRWNnS1F2MmUvWXdhRDFrNlZRWXdJREFR" \
    "QUJBb0lCQVFDV3oxdCtEbTZiYVVXVQp3cHk2Ri9lcTNVend0WURUWEx0RG0vWDJWQzFDcm5RMmhB" \
    "ODQ3dDB2TU9uNDV4aGRUdm1xaGJBYTRpYzUzZzZZCm04amRDeTlrQVRYOFVDc1JYdTVlMFk4YUNW" \
    "MEZlNmdjRDJrd0FyMU9wMmY3aE1nWTcwUlgrZnVjL2tWalEwQWwKV3pXM0dSNjV6bUJDYlZUNHNq" \
    "OHBxMG5wYndlYUk1UWZSdWpWUDMreGM5V1hJZi9BVm1zRnMxYmxwSTJxTE01TQpQdlI1SU1nUnhn" \
    "SlBrUVNhZWwrMk1nQmNpTnZrdVM1ZjFOem54a2RBQjNYMnd1NjdIR3J2R3ZwR0tzNDBqSDJPCi93" \
    "YThsaCtwTzZpSGR3YjlTYkxmUzV6UmV3NnR6c2NHakwvTGNmMUd1MzR5UUlQamxWdDZTYVNyajhN" \
    "R1JwcGIKaUR3QTZERHhBb0dCQVBBSmJZTVNXRU1ONDFyOVVVb1NCWXlMRk1ISElmeXdZNHZpNFA3" \
    "Q2F0cmkvcytBZS9BSQpRRjdxNGIrSjFkdlNqQ01mK1V4SkxWVzlmMWcvYVpqZE13UEFDL1E5Vm11" \
    "cGVjL3RnaStrOG83eEJMQ2FTL3BFCnJNQWZaZWR1NUwzMTc5cWcwSHZMOU5kTUFxMkNPeUp5Tzhq" \
    "KzFRUm9yTEpLbkZabC9WeXgveGlIQW9HQkFOUlcKdjZkdmtqS3BXcEVZcW5Md0dhZ3ZTWWx4S3d0" \
    "NDY0Ujl2WVRzUmNFNWhJTlpiVmFoZXZ6UlFpc09sNll1UTZsdQp5WjlZalROMEJrbFMrd21rd09x" \
    "dVd1RTlDRVc0dTdNNnlqZTFqclhlWWJQZDlyNmNFTlgxaCtQVHVtU2ozRzNwClE4Q0gzVGVIM2Fy" \
    "ZUdzeGRrVE1BdkF6RFJ3eG9EWkZYNGJydWo2eEZBb0dBUmZTNWNlVzZ5M0FVdnNQdEdRVS8Ka01K" \
    "SC9tR215aG91S09xcVlCVVJSMUc0cVlqc2xmd1JwcGdWeXRqRTl4Zlp0N0x0MlFuS3FKNWRxcjV3" \
    "YkJpcgpjWUJhKzRlVTFEUEVTSkVUekFicW1qWXNBN3cwUUhBYldMTE41REV4Z1J0WUdBT2VQells" \
    "MlVsUnpuZVIvR3dHCmVJR3NXMmlXVEMvcWVGT3BENGJncmFrQ2dZQVRuK1RjcTdJZVhvcVJTRzlR" \
    "YWlKazZlSHBBdjJRZE4rSGdqdUcKMG5OcjlVM3ErZFBpSXRDRUZ5Ny9YYnprVGZoUTYzMVU3ZEUz" \
    "QlMwamo3akYzbVU2QzEwNDNmUXF4WFVMam81cgo4YXE3NGs2eldmdFpDSUdCMU14M1lQVWtJZ1RZ" \
    "WDZ1MFdwbzJiS2N2Q0pIL2UxSlZIV2RENHJScFVDQ1k0ejlvCmtHM1U1UUtCZ1FEZjh3d08xYjZM" \
    "Y2VDdTFudCtNQkJSTEVxOXhHSHY5dzFVRFViM3AvRHJoUXhZS0Q4WUdQODAKb3FwS1c3MFZqa0pJ" \
    "dytNT3VaQjNuYk9wOE11UjMyNERqdTF3N3lXOEFOT0Rmd1M5WEo1VTlSU2VIdG5DVjdhdgpDbWt4" \
    "OGRXc3BJUURxUnRwSkx4WDBYS2g1TDlab3JEZXNuYzcrd3p3d1NyMzQrTlIrdlAxR1E9PQotLS0t" \
    "LUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=" \
    /* end */

// raytight/ums/client.crt.c
#define OEM1_UMS_CERT \
    "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5VENDQWJHZ0F3SUJBZ0lKQUpOU0RDTWtL" \
    "UUhITUEwR0NTcUdTSWIzRFFFQkN3VUFNQmt4RnpBVkJnTlYKQkFNTURpb3VjbUY1ZEdsbmFIUXVZ" \
    "Mjl0TUI0WERURTJNREV4TXpBMU16SXdORm9YRFRNMk1ERXdPREExTXpJdwpORm93RmpFVU1CSUdB" \
    "MVVFQXd3TEtpNXNkR1ZtYVM1amIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdn" \
    "Z0VLQW9JQkFRREhHU1dQWExHbnU4VEowb1lLMm84N2tVVC82M1oxZ04xTHNIZThKVnJKY3RiSDBt" \
    "YXcKbFhWa2VsNldYRnRTSlhtbzJEdW9na3VmQ1N2ZzU5emxYQTJtdnovbThzNHVocGdvclcxTE0x" \
    "NVFiazN6V2szZAoxeFRaK2YyRTVkbzRDc3Q5QVdrdmhvNXhML3krYzhJQlN5VlIvWTVUTGRlSjl0" \
    "eDM1cHJxN3dTNEwvYlRPNU0yCjU2dHN4Z0lzUFE5Nnc0c2pWWStqQVZCNXVuUkZ2MjM0MzZCaVdU" \
    "UExSYjJVUGl0NnQ5U0VLRE56Wk04UnM3dGcKWllPTEJOZVRpRUdXc0lwNk1LR2xnZ3BXVk1Eblha" \
    "Q0k1QWtVVUVkQnBZS3piTkhBb3VVNTBCM1BMZjJnWGJrOQpTMEo1Q1RRQ0pKbzZkbStnQVJ5QXBD" \
    "L1o3OWpCb1BXVHBWQmpBZ01CQUFHakZ6QVZNQk1HQTFVZEpRUU1NQW9HCkNDc0dBUVVGQndNQ01B" \
    "MEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQStDamdMNThKMHZCcktjb3ZTMng0b0JnZ0YKa0tGNVgv" \
    "Yk95cU91N1R3VlRRQnZrV3B0dk5FaEJtTWFjTWJlMm5YUUxxNDR5UTFDUVJDdmVuaHN1OWl3WmJr" \
    "ZwpHK3BBT0tuNTJuY0krSFllZlhTMWNCc0w1ZkMvOUt2SFFOVHFpSW8yM1Q3MlorQXcrL3c5M0ow" \
    "d3l5WWJieFJMClVkSVVURVFwL2RCZjl2NEVEdkZpbzJRam4xRzg1dUZ3SHpVRVlvU2wxTjZBYnh4" \
    "bUlxdlB6YkorQTMva25ESFoKL3FHbWt5b1V2OWhPdC8xMlI1TzgwVGQ4aUZWeUllci9NVlZyRU15" \
    "eFpJa1cxVWNxeWtBLzNZc09Fdll3V0pPMwpjSUR5Z3lIWmlNMFlSWFdMc3Y2SWw5aC8rQUFzYVBL" \
    "K3dwaFloSmdYejIvSHY2amxEWjRMTEpCTmhaTGcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=" \
    /* end */

#define OEM1_CERT_UMS_INITER     {  \
    [OEM_CERT_CA]   = OEM1_UMS_CA,  \
    [OEM_CERT_KEY]  = OEM1_UMS_KEY, \
    [OEM_CERT_CERT] = OEM1_UMS_CERT,\
}   /* end */

#define OEM1_CERT_INITER                    {   \
    .cert = {                                   \
        [OEM_APP_LMS] = OEM1_CERT_LMS_INITER,   \
        [OEM_APP_LSS] = OEM1_CERT_LSS_INITER,   \
        [OEM_APP_UMS] = OEM1_CERT_UMS_INITER,   \
    },                                          \
}

#define OEM1_INITER __OEM_INITER( \
    OEM1_BASE_INITER,    \
    OEM1_RSYNC_INITER,   \
    OEM1_LSS_INITER,     \
    OEM1_CERT_INITER)
/******************************************************************************/
#endif /* __LIB_OEM_OEM1_H__ */
